name: nicemusic
description: nicemusic.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.9
  fluttertoast: ^3.0.4
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.17.4
  flutter_swiper: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf